version: 2
jobs:
  build:
    # machine: true
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      # - setup_remote_docker:
      - run:
          command: |
            whoami
            go version
