version: 2
jobs:
  build:
    docker:
      - image: coqorg/coq:8.8
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: 'coqc --version'
